### ISSUE TITLE
Performance drops when training on multiple routes

### ISSUE THREAD

**Issue by sanjay-subramanya** [Tejas-Deo/Safe-Navigation-Training-Autonomous-Vehicles-using-Deep-Reinforcement-Learning-in-CARLA#5]
Hi Tejas, thank you for making this repo public. 
I've been trying to train the Driving DQN on multiple routes in the same town, where in the original script, it trains on only 2 routes. Even after multiple attempts, the performance of the agent was quite poor and it was struggling to complete turns on time. 
What could be done to improve this? Any help/advice would be appreciated, thanks!

**Comment by zdy1013** [comment]
Dude, how many rewards can you drive the model to? Why can't I run more than 4000

**Comment by Tejas-Deo** [comment]
> Hi Tejas, thank you for making this repo public. I've been trying to train the Driving DQN on multiple routes in the same town, where in the original script, it trains on only 2 routes. Even after multiple attempts, the performance of the agent was quite poor and it was struggling to complete turns on time. What could be done to improve this? Any help/advice would be appreciated, thanks!


Hi Sanjay,
Training a DQN takes a lot of time. For the most of the training part, the model won't perform better than a random model and then would drastically start performing well. I would recommend leaving the model to train for at least a day to check the performance. I would also recommend using a Double DQN instead of of DQN as it resolves the overestimation issue of DQNs and would be able to generalize better. Hope this helps.
